### ISSUE TITLE
How to generate spherical embedding for meshes?

### ISSUE THREAD

**Issue by kuwan2e** [patr-schm/surface-maps-via-adaptive-triangulations#1]
Hello, I want to try some data made by myself. But it seems that I need to generate spherical embedding for my mesh first.
So could you please tell me How to generate spherical embedding for meshes?
Thanks!

**Comment by patr-schm** [comment]
Hi! Have a look at [init_map(..)](https://github.com/patr-schm/surface-maps-via-adaptive-triangulations/blob/da768497f0b8a84088b7f0d839b8b40a1780c672/src/SurfaceMaps/AdaptiveTriangulations/InitSphereEmbeddings.cc#L69C61-L69C61), where we call `multi_res_sphere_embedding(..)`.

The function decimates a genus-0 mesh to a tetrahedron, embeds it on the sphere, and then bijectively re-inserts all vertices (one independent set at a time). This is interleaved with a few iterations of global optimization. Depending on your input, this might need some parameter tuning. See settings [here](https://github.com/patr-schm/surface-maps-via-adaptive-triangulations/blob/main/src/SurfaceMaps/MultiRes/MultiResSphereEmbeddingSettings.hh).
